FROM registry.fedoraproject.org/fedora-toolbox:41

RUN sed -i "s/enabled=1/enabled=0/" /etc/yum.repos.d/fedora-cisco-openh264.repo \
    && dnf -y update \
# distrobox wants this, read more at setup_dnf() at
# https://github.com/89luca89/distrobox/blob/18053c254a83750c49c08e58df2e48a0f04aef48/distrobox-init#L861
# https://github.com/89luca89/distrobox/blob/main/docs/posts/distrobox_custom.md
    && dnf -y install \
       pinentry \
# Install packages 
    && dnf -y install \
        bat \
        eza \
        fd \
        zoxide \
        fzf \
        jq \
        just \
        make \
        ripgrep \
    && dnf -y --setopt=install_weak_deps=False install \
        go \
    && dnf -y swap nano-default-editor vim-default-editor --allowerasing \
    && dnf clean all

# Add starship
RUN sh <(curl -sS https://starship.rs/install.sh) -y \
    && echo 'eval "$(starship init bash)"' >> /etc/bashrc

# Add atuin
RUN  curl --proto '=https' --tlsv1.2 -LsSf https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o /etc/skel/.bash-preexec.sh \
    && echo '[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh' >> /etc/bashrc \
    && sh <(curl --proto '=https' --tlsv1.2 -LsSf https://github.com/atuinsh/atuin/releases/latest/download/atuin-installer.sh) \
    && install -m 0755 /root/.atuin/bin/atuin /usr/bin/atuin \
    && echo 'eval "$(atuin init bash)"' >> /etc/bashrc

# Link binaries on the host
RUN binaries=( \
    "code" \
    "btop" \
    "flatpak" \
    "htop" \
    "podman" \
    "rpm-ostree" \
    "systemctl" \
    "xdg-open" \
    "skopeo" \
    "tmux" \
    ); \
    for bin in "${binaries[@]}"; do \
        ln -s /usr/bin/distrobox-host-exec /usr/local/bin/$bin;\
    done
