name: Build bftOS
on:
  schedule:
    - cron: "25 6 * * *" # Everyday 6:25 (40 min after upstream)
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-desktop-stable:
    uses: ./.github/workflows/build-desktop.yml
    secrets: inherit
    with:
      tag_version: stable
