name: Build bftOS Desktop
on:
  schedule:
    - cron: "25 6 * * *" 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-desktop-stable:
    name: Desktop Stable
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      images: '["bluefin", "bluefin-dx"]'
      streams: '["stable"]'
      flavors: '["main"]'

