name: Build and Push bftOS Toolbox
on:
  workflow_call:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_STYLED: bftOS

jobs:
  build-image:
    name: Build Toolbox
    runs-on: ubuntu-24.04
    continue-on-error: false
    strategy:
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Checkout Push to Registry Action
        uses: actions/checkout@v4

      - name: Setup Just
        id: setup_just
        shell: bash
        run: |
          set -eoux pipefail
          JUST_VERSION=$(curl -L https://api.github.com/repos/casey/just/releases/latest | jq -r '.tag_name')
          curl -sSLO https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz
          sudo tar -zxvf just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz -C /usr/local/bin just
          rm -f just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz

      - name: Build Toolbox
        id: build_toolbox
        shell: bash
        run: |
          sudo just build-toolbox 

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR
        id: push
        if: github.event_name != 'pull_request'
        uses: Wandalen/wretry.action@v3.7.2
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            set -euox pipefail

            sudo podman push bftos:toolbox ${{ steps.registry_case.outputs.lowercase }}/bftos:toolbox
            digest=$(sudo skopeo inspect docker://${{ steps.registry_case.outputs.lowercase }}/bftos:toolbox --format '{{.Digest}}')
            echo "digest=${digest}" >> $GITHUB_OUTPUT

      - uses: sigstore/cosign-installer@v3.7.0
        if: github.event_name != 'pull_request'

      - name: Sign Container Image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/bftos@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.outputs && fromJSON(steps.push.outputs.outputs).digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Echo Outputs
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
